#!/bin/bash

DIRPHPAPACHE=php-apache
DIRPOSTGRES=postgres

PHPAPACHEIMAGES=(apache)
POSTGRESIMAGES=(latest)

for PHPAPACHEIMAGE in ${PHPAPACHEIMAGES[@]}
do
  if [ ! -d $DIRPHPAPACHE/$PHPAPACHEIMAGE ]; then
    mkdir $DIRPHPAPACHE/$PHPAPACHEIMAGE
  fi

  cp $DIRPHPAPACHE/Dockerfile $DIRPHPAPACHE/$PHPAPACHEIMAGE
  cp $DIRPHPAPACHE/config.ini $DIRPHPAPACHE/$PHPAPACHEIMAGE
  cp $DIRPHPAPACHE/vhost.conf $DIRPHPAPACHE/$PHPAPACHEIMAGE

  sed -i "1s/<PHPAPACHEIMAGE>/php:${PHPAPACHEIMAGE}/" $DIRPHPAPACHE/$PHPAPACHEIMAGE/Dockerfile
done

for POSTGRESIMAGE in ${POSTGRESIMAGES[@]}
do
  if [ ! -d $DIRPOSTGRES/$POSTGRESIMAGE ]; then
    mkdir $DIRPOSTGRES/$POSTGRESIMAGE
  fi

  cp $DIRPOSTGRES/Dockerfile $DIRPOSTGRES/$POSTGRESIMAGE

  sed -i "1s/<POSTGRESIMAGE>/postgres:${POSTGRESIMAGE}/" $DIRPOSTGRES/$POSTGRESIMAGE/Dockerfile
done
